### ISSUE TITLE
tpr breaks chunks 1.17.1

### ISSUE THREAD

**Issue by aladushkaoya** [EssentialsX/Essentials#4532]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=3b5ecd03f68b448a81eee7cbe49f63d3

### Bug description

Sorry for translate.google

I tried both with the stable version and with the dev assembly

When you use the / tpr command, the chunks loaded from it break, I'm not sure if it's ticks or something else, but here are some examples of what breaks: sounds lose their position, that is, are played from the back when they should be in front of me; items drop breaks, they appear in the wrong place; THE MOST IMPORTANT FOR A DEBUG: when a creeper explodes (let's say with a lighter, it's faster), phantom blocks appear in such chunks in the funnel, when you click on them with RMB, they immediately reappear

### Steps to reproduce

1.use /tpr
2.take creeper egg
3.light him
4.try RMB on air blocks, if nothing happens, retry step 2,3
5.PROFIT! the blocks are returned to their place

### Expected behaviour

normal chunks, tick, and other

### Actual behaviour

Laggy chunks, ticks

**Comment by Laarryy** [comment]
I have been able to intermittently reproduce this using only EssentialsX 2.19.1-dev+12-ef8bcc8 and Paper 1.17.1 #304.

Used exactly the steps as described - does not work all of the time but can be made to work if you try a few times.

**Comment by JRoy** [comment]
After consulting with more of the Paper developers, this is a client side issue and **cannot** be fixed by EssentialsX.

The client handles a lot of the actual logic for explosions and when you combine that with teleporting out into far distances which the client isn't tested with very often, that's how you get this behavior

**Comment by pop4959** [comment]
I'd like to add based on what JRoy mentioned above, it sounds like a reasonable solution would be to consider reducing your world size, or at the very least, the distance that players are allowed to randomly teleport with `/settpr`, so that you do not experience this issue.

**Comment by aladushkaoya** [comment]
it is not entirely clear how it works on the client side, if when you go to the server or when you restart the server, this problem is not solved, rather it is on the server side, and you, as a plugin, need to either change the method of teleportation, or even remove such functionality from the plugin, I do not quite understand how you reacted to this problem, because when teleporting using minecraft tools, this does not happen...

**Comment by JRoy** [comment]
> it is not entirely clear how it works on the client side, if when you go to the server or when you restart the server, this problem is not solved, rather it is on the server side, and you, as a plugin, need to either change the method of teleportation, or even remove such functionality from the plugin, I do not quite understand how you reacted to this problem, because when teleporting using minecraft tools, this does not happen...

![image](https://user-images.githubusercontent.com/10731363/138595767-c7c9913e-31c9-465d-9684-94258c55c55b.png)

**Comment by aladushkaoya** [comment]
and as far as I understand, this problem will not be solved by limiting the range of teleports, and the size of the world, it also has nothing to do with long distances, teleport using the command `/tp x y z` works as it should, without any lags, and that's when using tpr, all chunks loaded from this moment will cause problems, my assumption is that this is due to some kind of out-of-sync, and it is clear that this out-of-sync is created by your plugin, neither the server nor the client of such behavior will ever not experienced, only after tpr, I think you need to dig deeper into this problem, it really creates an incredible disaster for the server, even after removing the plugin, the world still behaves inadequately.

**Comment by aladushkaoya** [comment]
This has nothing to do with large coordinates, it is exclusively TP in any non-loaded chunk
