### ISSUE TITLE
Socialspy prefix colour formatting is missing the less-than symbol

### ISSUE THREAD

**Issue by MODNMETL** [EssentialsX/Essentials#5828]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=96e21f7d189e4c3480d6777965f57a67

### Bug description

When the socialspy messages are displayed for staff to monitor there is a missing < in the minimessage colour code for aqua causing it to format incorrectly. (see image example)
![image](https://github.com/EssentialsX/Essentials/assets/89078751/c2ab8e3d-7c35-46ef-8198-9e4b0b76462f)

### Steps to reproduce

View socialspy message in-game with 2.21.0-dev+93-3a6fdd9 Essentials installed (TBH it's been there for a number of releases, I just figured you'd have picked it up by now so didn't bother reporting it as it's such a minor issue)

### Expected behaviour

For the socialspy messages to have the correct prefix format

### Actual behaviour

The colour code is visible as "aqua>"

**Comment by JRoy** [comment]
Could you share the translation line you're using?

**Comment by MODNMETL** [comment]
> Could you share the translation line you're using?

Sorry, could you clarify what you're after exactly? Which yml file would it be in?

**Comment by Evidentsinger14** [comment]
Your custom locale file. It would be in `/plugins/Essentials/messages/` and Called something like messages_en.properties

**Comment by MODNMETL** [comment]
> Your custom locale file. It would be in `/plugins/Essentials/messages/` and Called something like messages_en.properties

There's nothing in the /plugins/Essentials/messages folder and no messages_en file anywhere else either

**Comment by makegodhere** [comment]
me to

**Comment by Evidentsinger14** [comment]
Confirmed - this is with chat radius enabled, and the staff member being outside of the local radius. 
![image](https://github.com/user-attachments/assets/b32b75d0-68c3-4969-ac5b-999f11a49c8c)

**Comment by JRoy** [comment]
Cannot reproduce, I'm pretty sure I fixed this in b293f2328a1f86cef23d80d6fa07abfd476aba80

Will re-open if not the case.

**Comment by makegodhere** [comment]
@JRoy not fixed

![Image](https://github.com/user-attachments/assets/9f78f9d2-36ee-4a6d-93a9-a44c676d092a)

![Image](https://github.com/user-attachments/assets/bdf4572e-d10a-40fd-825b-c11163655dc2)

![Image](https://github.com/user-attachments/assets/bd593cae-6847-4f46-8a3c-14323342fc7e)

![Image](https://github.com/user-attachments/assets/0f18affd-3c40-4e7b-b15a-bfc37894238d)

messages folder is clear

![Image](https://github.com/user-attachments/assets/95d37dc3-3605-4192-913f-2c865b50c17d)

**Comment by MODNMETL** [comment]
Yep, confirmed as not fixed, even with the latest 2.21.0 EssentialsX we still have this display bug on our 1.21.4 server.

**Comment by VideoGamerRUS** [comment]
Still in 2.21.1 

<img width="512" height="25" alt="Image" src="https://github.com/user-attachments/assets/b8cc0a68-3577-4583-8830-b8fc86a57ad5" />
