### ISSUE TITLE
I get "Missing artifact" when using Essentials with Maven

### ISSUE THREAD

**Issue by NorbiPeti** [EssentialsX/Essentials#886]
I have these in my pom.xml (at the repositories and dependencies tags):

```
        <repository>
            <id>Essentials</id>
            <url>https://ci.drtshock.net/plugin/repository/everything/</url>
        </repository>

        <dependency>
            <groupId>net.ess3</groupId>
            <artifactId>EssentialsX</artifactId>
            <version>2.0.1</version>
        </dependency>
```

And I get this:

> Missing artifact net.ess3:EssentialsX:jar:2.0.1

Looking at the lastUpdated file in my local repository doesn't show anything helpful either:

> https://ci.drtshock.net/plugin/repository/everything/.error=

**Comment by SupaHam** [comment]
For whatever reason it was changed to `https://ci.drtshock.net/plugin/repository/`

**Comment by NorbiPeti** [comment]
Changing to that URL didn't solve the problem for me. I still get "Missing artifact".

**Comment by SupaHam** [comment]
See #877 for now

**Comment by mawkews** [comment]
@SupaHam I have a similar issue, I have the same in my pom file but I get this:  

> Failed to read artifact descriptor for net.ess3:EssentialsX:jar:2.0.1: Could not transfer artifact net.ess3:EssentialsParent:pom:2.0.1 from/to vault-repo (http://nexus.theyeticave.net/content/repositories/pub_releases): nexus.theyeticave.net: Unknown host nexus.theyeticave.net

**Comment by SupaHam** [comment]
@Markersx I'm not entirely sure there is a good permanent fix. For now I would highly recommend that you locall `mvn install` this project and whenever changes happen that concern you, simply `git pull` and `mvn install`.

**Comment by mawkews** [comment]
I'm not sure how, why or what happened but the problem is fixed this is what I have in my pom.xml


```
   <dependency>
        <groupId>net.ess3</groupId>
        <artifactId>EssentialsXParent</artifactId>
        <version>2.0.1</version>
    </dependency>

    <dependency>
        <groupId>net.ess3</groupId>
        <artifactId>EssentialsX</artifactId>
        <version>2.0.1</version>
        <scope>provided</scope>
        <exclusions>
            <exclusion>
                <groupId>org.bukkit</groupId>
                <artifactId>bukkit</artifactId>
            </exclusion>
            <exclusion>
                <groupId>org.bukkit</groupId>
                <artifactId>craftbukkit</artifactId>
            </exclusion>
            <exclusion>
                <groupId>mkremins</groupId>
                <artifactId>fanciful</artifactId>
            </exclusion>
            <exclusion>
                <groupId>com.comphenix.protocol</groupId>
                <artifactId>ProtocolLib</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

    <repository>
        <id>drtshock-repo</id>
        <url>http://ci.drtshock.net/plugin/repository/everything</url>
    </repository>

    <repository>
        <id>ess-repo</id>
        <url>http://repo.ess3.net/content/groups/essentials</url>
    </repository>
```

I could probably remove http://repo.ess3.net/content/groups/essentials right?

**Comment by enzanki-ars** [comment]
I am also having this issue.  There seems to be nothing in the directories for the repo.

**Comment by PyvesB** [comment]
Unfortunately, the problem still seems outstanding almost a year later. It is not possible to set EssentialsX as a Maven dependency in other projects.

**Comment by SupaHam** [comment]
Working on it.

**Comment by mikroskeem** [comment]
Bump

**Comment by mdcfe** [comment]
You should now be able to use `https://ci.ender.zone/plugin/repository/everything/` as the Maven repo for EssentialsX (as well as PlayerVaultsX and FactionsUUID).
